=== sgm51357/nonpolar/commons/data-sync/2.2/target/classes/sync-1.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="dataConvert">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" name="data">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="1" minOccurs="1" name="fields">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element maxOccurs="unbounded" minOccurs="0" name="field">
											<xsd:complexType mixed="true">
												<xsd:attribute name="target" type="xsd:string" />
												<xsd:attribute name="unique" type="xsd:boolean" />
												<xsd:attribute name="default" type="xsd:string" />
												<xsd:attribute name="mapping" type="xsd:string" />
												<xsd:attribute name="convert" type="xsd:string" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element maxOccurs="1" minOccurs="0" name="params">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element maxOccurs="unbounded" minOccurs="1" name="param">
											<xsd:complexType mixed="true">
												<xsd:attribute name="target" type="xsd:string" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element maxOccurs="1" minOccurs="0" name="defaultValues">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element maxOccurs="unbounded" minOccurs="1" name="defaultValue">
											<xsd:complexType mixed="true">
												<xsd:attribute name="target" type="xsd:string" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element maxOccurs="1" minOccurs="0" name="updateExcludes">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element maxOccurs="unbounded" minOccurs="1" name="updateExclude">
											<xsd:complexType mixed="true">
												<xsd:attribute name="target" type="xsd:string" />
												<xsd:attribute name="model">
													<xsd:simpleType>
														<xsd:restriction base="xsd:string">
															<xsd:enumeration value="update" />
															<xsd:enumeration value="force" />
															<xsd:enumeration value="conflict" />
															<xsd:enumeration value="zero" />
														</xsd:restriction>
													</xsd:simpleType>
												</xsd:attribute>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element maxOccurs="1" minOccurs="0" name="valueExcludes">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element maxOccurs="unbounded" minOccurs="1" name="valueExclude">
											<xsd:complexType mixed="true">
												<xsd:attribute name="target" type="xsd:string" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="typeCode" type="xsd:string" />
						<xsd:attribute name="class" type="xsd:string" />
						<xsd:attribute name="fullName" type="xsd:string" />
						<xsd:attribute name="increName" type="xsd:string" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="1" name="notifys">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="unbounded" minOccurs="0" name="notify">
								<xsd:complexType mixed="true">
									<xsd:attribute name="appType" type="xsd:string" />
									<xsd:attribute name="appCode" type="xsd:string" />
									<xsd:attribute name="relativePath" type="xsd:string" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="fileSuffix" default="csv">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="csv" />
						<xsd:enumeration value="xml" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="encoding" type="xsd:string" default="UTF-8" />
			<xsd:attribute name="updateRecoder" type="xsd:string" default="updateRecoder" />
			<xsd:attribute name="relativePath" type="xsd:string" />
			<xsd:attribute name="cleanHistory" type="xsd:int" />
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== sgm51357/nonpolar/commons/data-sync/2.2/src/test/resources/in/vmses/vms1/vms.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataConvert xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" encoding="UTF-8" relativePath="/resFiles/"
	updateRecoder="updateRecoder" xsi:noNamespaceSchemaLocation="../sync-1.1.xsd">
	<!-- CONTROL_UNIT -->
	<data class="vision.apollo.rmp.common.domain.ResTreeNode" typeCode="CONTROL_UNIT">
		<fields>
			<field target="indexCode" unique="true" />
			<field target="name" />
			<field target="parentIndexCode" />
			<field target="seqIdx"/>
		</fields>
		<defaultValues>
			<defaultValue target="exsit">1</defaultValue>
			<defaultValue target="treeCode">vision_base_tree</defaultValue>
			<defaultValue target="unitType">1</defaultValue>
		</defaultValues>
		<updateExcludes>
			<updateExclude target="createTime" model="force" />
			<updateExclude target="updateTime" model="force"/>
		</updateExcludes>
		<params>
			<param target="unitType">1</param>
		</params>
	</data>
	<!-- REGION_INFO -->
	<data class="vision.apollo.rmp.common.domain.ResTreeNode" typeCode="REGION_INFO">
		<fields>
			<field target="indexCode" unique="true" />
			<field target="name" />
			<field target="parentIndexCode" />
			<field target="seqIdx"/>
		</fields>
		<defaultValues>
			<defaultValue target="exsit">1</defaultValue>
			<defaultValue target="treeCode">vision_base_tree</defaultValue>
			<defaultValue target="unitType">2</defaultValue>
		</defaultValues>
		<updateExcludes>
			<updateExclude target="createTime" model="force" />
			<updateExclude target="updateTime" model="force"/>
		</updateExcludes>
		<params>
			<param target="unitType">2</param>
		</params>
	</data>
	<!-- DEVICE_INFO -->
	<data class="java.util.Map" typeCode="DEVICE_INFO">
		<fields>
			<field target="originalIndexcode" unique="true" />
			<field target="name" />
			<field target="treeNodeIndexcode" />
			<field target="isOnline" mapping="0:1,1:0"/>
			<field target="deviceType" />
			<field target="networkAddr" />
			<field target="networkPort" />
			<field target="userName" />
			<field target="userPwd" />
			<field target="seqIdx"/>
			<field target="relateUserId" />
			<field target="defenseStatus" />
		</fields>
		<defaultValues>
			<defaultValue target="enable">1</defaultValue>
			<defaultValue target="typeCode">DEVICE_INFO</defaultValue>
		</defaultValues>
		<updateExcludes>
			<updateExclude target="createTime" model="force" />
			<updateExclude target="updateTime" model="force"/>
		</updateExcludes>
	</data>
	<!-- CAMERA_INFO -->
	<data class="java.util.Map" typeCode="CAMERA_INFO">
		<fields>
			<field target="originalIndexcode" unique="true" />
			<field target="name" />
			<field target="treeNodeIndexcode" />
			<field target="isOnline" mapping="0:1,1:0"/>
			<field target="decodeTag" />
			<field target="longitude" />
			<field target="latitude" />
			<field target="elevation" />
			<field target="pixel" />
			<field target="cameraType" />
			<field target="recordPos" />
			<field target="recLocation" />
			<field target="deviceIdx" />
			<field target="installPlace" />
			<field target="matrixCode" />
			<field target="chanNum" />
			<field target="seqIdx"/>
			<field target="cascadeCode"/>
		</fields>
		<defaultValues>
			<defaultValue target="isOnline">0</defaultValue>
			<defaultValue target="enable">1</defaultValue>
			<defaultValue target="typeCode">CAMERA_INFO</defaultValue>
		</defaultValues>
		<updateExcludes>
			<updateExclude target="recLocation" model="forceUpdate" />
			<updateExclude target="longitude" model="zero" />
			<updateExclude target="latitude" model="zero" />
			<updateExclude target="createTime" model="force" />
			<updateExclude target="updateTime" model="force"/>
		</updateExcludes>
	</data>
	<!-- IO_INFO -->
	<data class="java.util.Map" typeCode="IO_INFO">
		<fields>
			<field target="originalIndexcode" unique="true" />
			<field target="name" />
			<field target="treeNodeIndexcode" />
			<field target="deviceIdx" />
			<field target="ioType" />
			<field target="chanNum" />
		</fields>
		<defaultValues>
			<defaultValue target="enable">1</defaultValue>
			<defaultValue target="typeCode">IO_INFO</defaultValue>
		</defaultValues>
		<updateExcludes>
			<updateExclude target="createTime" model="force" />
			<updateExclude target="updateTime" model="force"/>
		</updateExcludes>
	</data>
	<!-- TVWALL_INFO -->
	<data class="java.util.Map" typeCode="TVWALL_INFO">
		<fields>
			<field target="originalIndexcode" unique="true" />
			<field target="name" />
			<field target="treeNodeIndexcode" />
			<field target="tvmsIndexCode" />
		</fields>
		<defaultValues>
			<defaultValue target="enable">1</defaultValue>
			<defaultValue target="typeCode">TVWALL_INFO</defaultValue>
		</defaultValues>
		<updateExcludes>
			<updateExclude target="createTime" model="force" />
			<updateExclude target="updateTime" model="force"/>
		</updateExcludes>
	</data>
</dataConvert>
